target 'DMPasscode', :exclusive => true do
  pod "DMPasscode", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DMPasscode", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'GRAESCrypt', '~> 1.0'
end
